platform :ios, '10.0'

project 'MobileContentGuide.xcodeproj'
target 'MobileContentGuide' do

source 'https://github.com/CocoaPods/Specs.git'

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'tvOS',
    'jschelpers',
    'cxxreact',
    'CxxBridge',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
]

pod 'SalesforceAnalytics', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceReact', :path => '../mobile_sdk/SalesforceMobileSDK-iOS'

  # pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

end

# Fix for xcode9/fmdb/sqlcipher/cocoapod issue - see https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27
post_install do | installer |
  print "SQLCipher: link Pods/Headers/sqlite3.h"
  system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
  copy_pods_resources_path = "Pods/Target Support Files/Pods-MobileContentGuide/Pods-MobileContentGuide-resources.sh"

    string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'

    assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'

    text = File.read(copy_pods_resources_path)

    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)

    File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
end
